//! Neovim demo for canopy-lsp
//!
//! Launches Neovim with canopy-lsp configured using the new vim.lsp.config API.
//!
//! # Usage
//!
//! ```bash
//! cargo run -p canopy-lsp --example nvim_demo --release
//! ```
//!
//! # Requirements
//!
//! - Neovim 0.11+ (uses vim.lsp.config and vim.lsp.enable)
//! - canopy-lsp binary (built automatically in release mode)

use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    // Find project root (where Cargo.toml is)
    let manifest_dir = env!("CARGO_MANIFEST_DIR");
    let crate_dir = PathBuf::from(manifest_dir);

    // Locate the canopy-lsp binary
    let lsp_binary = find_lsp_binary(&crate_dir)?;
    println!("Using LSP binary: {}", lsp_binary.display());

    // Paths to our lua files
    let lua_dir = crate_dir.join("lua");
    let canopy_lua = lua_dir.join("canopy.lua");
    let sample_file = lua_dir.join("sample.txt");

    // Verify files exist
    if !canopy_lua.exists() {
        return Err(format!("canopy.lua not found at {}", canopy_lua.display()).into());
    }
    if !sample_file.exists() {
        return Err(format!("sample.txt not found at {}", sample_file.display()).into());
    }

    // Create a temporary init.lua that loads our config
    let temp_dir = tempfile::tempdir()?;
    let init_lua = temp_dir.path().join("init.lua");

    let init_content = format!(
        r#"-- Canopy LSP Demo init.lua
-- Auto-generated by nvim_demo example

-- Add the crate directory to runtimepath so require("canopy") finds lua/canopy.lua
vim.opt.runtimepath:prepend("{crate_dir}")

-- Load and setup canopy LSP
local canopy = require("canopy")
canopy.setup("{lsp_path}")

-- Basic editor settings for demo
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.signcolumn = "yes"
vim.opt.updatetime = 250

-- Show diagnostics in virtual text
vim.diagnostic.config({{
  virtual_text = true,
  signs = true,
  underline = true,
  update_in_insert = false,
}})

-- Set leader key
vim.g.mapleader = " "

print("Canopy LSP Demo - press K to hover, <Space>ca for code actions, <Space>ih to toggle hints")
"#,
        crate_dir = crate_dir.display().to_string().replace('\\', "/"),
        lsp_path = lsp_binary.display().to_string().replace('\\', "/"),
    );

    fs::write(&init_lua, init_content)?;

    println!("\nLaunching Neovim with Canopy LSP...");
    println!("  Config: {}", init_lua.display());
    println!("  Sample: {}", sample_file.display());
    println!("\nKeybindings:");
    println!("  K          - Hover (show semantic info)");
    println!("  <Space>ca  - Code actions");
    println!("  <Space>ih  - Toggle inlay hints");
    println!("  <Space>d   - Show diagnostic float");
    println!("  [d / ]d    - Navigate diagnostics");
    println!("  :LspInfo   - Check LSP status");
    println!();

    // Launch neovim
    let status = Command::new("nvim")
        .arg("--clean")
        .arg("-u")
        .arg(&init_lua)
        .arg(&sample_file)
        .env("CANOPY_LSP_PATH", &lsp_binary)
        .status()?;

    if !status.success() {
        return Err(format!("Neovim exited with status: {status}").into());
    }

    Ok(())
}

/// Find the canopy-lsp binary, checking common locations
fn find_lsp_binary(crate_dir: &Path) -> Result<PathBuf, Box<dyn std::error::Error>> {
    // Try to find workspace root (3 levels up from crate)
    let workspace_root = crate_dir
        .parent() // crates/
        .and_then(|p| p.parent()) // canopy/
        .ok_or("Could not find workspace root")?;

    // Check release build first (recommended)
    let release_binary = workspace_root
        .join("target")
        .join("release")
        .join("canopy-lsp");
    if release_binary.exists() {
        return Ok(release_binary);
    }

    // Check debug build
    let debug_binary = workspace_root
        .join("target")
        .join("debug")
        .join("canopy-lsp");
    if debug_binary.exists() {
        return Ok(debug_binary);
    }

    // Try building it
    println!("canopy-lsp binary not found, building in release mode...");
    let status = Command::new("cargo")
        .args(["build", "-p", "canopy-lsp", "--release"])
        .current_dir(workspace_root)
        .status()?;

    if !status.success() {
        return Err("Failed to build canopy-lsp".into());
    }

    if release_binary.exists() {
        return Ok(release_binary);
    }

    Err("Could not find or build canopy-lsp binary".into())
}
